export interface ToolConfig {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  description: string;
  benefits: string[];
  howItWorks: { step: string; title: string; description: string }[];
  faqs: { question: string; answer: string }[];
  relatedTools: string[];
}

export const toolConfigs: Record<string, ToolConfig> = {
  "remove-photo-metadata": {
    slug: "remove-photo-metadata",
    title: "Remove Photo Metadata",
    metaTitle: "Remove Photo Metadata Online Free — EXIF, GPS, Camera Info | MetaClean",
    metaDescription: "Remove EXIF data, GPS coordinates, camera information, and timestamps from photos instantly. Free client-side tool. Your files never leave your device.",
    keywords: [
      "remove photo metadata",
      "remove EXIF data",
      "EXIF remover online",
      "strip metadata from photos",
      "remove GPS from photo",
      "photo privacy tool",
      "remove camera info from photo",
      "free metadata remover",
      "client-side EXIF removal",
      "JPG metadata remover",
      "PNG metadata remover",
      "WEBP metadata remover",
    ],
    description: "Remove all metadata from your photos including EXIF data, GPS coordinates, camera information, device details, software tags, and timestamps. Supports JPG, JPEG, PNG, and WEBP formats.",
    benefits: [
      "Protect your location privacy by removing GPS coordinates",
      "Prevent device identification by stripping camera info",
      "Remove timestamps that reveal when photos were taken",
      "Clean software tags that expose your editing tools",
      "Keep your photos safe for social media sharing",
      "100% client-side processing — files never leave your device",
    ],
    howItWorks: [
      { step: "01", title: "Upload Photo", description: "Drag and drop or click to upload your JPG, JPEG, PNG, or WEBP image." },
      { step: "02", title: "Review Metadata", description: "See all detected metadata including GPS, camera info, timestamps, and more." },
      { step: "03", title: "Select & Clean", description: "Choose which metadata to remove and click Clean. Download your privacy-safe photo." },
    ],
    faqs: [
      { question: "What metadata is stored in photos?", answer: "Photos can contain EXIF data including GPS coordinates, camera make and model, lens information, aperture, shutter speed, ISO, timestamps, software used for editing, and author information. This metadata is embedded in the image file and can be read by anyone." },
      { question: "How do I remove EXIF data from photos?", answer: "Upload your photo to MetaClean's Photo Metadata Remover. The tool will automatically detect all metadata. Select which fields to remove and click Clean. The cleaned photo is downloaded directly to your device — no server upload required." },
      { question: "Is it safe to use online metadata removers?", answer: "Most online metadata removers upload your files to their servers, which is a privacy risk. MetaClean is different — all processing happens in your browser using client-side JavaScript. Your files never leave your device, making it completely safe." },
      { question: "What photo formats are supported?", answer: "MetaClean supports JPG, JPEG, PNG, and WEBP image formats. These cover the vast majority of photos taken by smartphones, digital cameras, and screenshots." },
      { question: "Does removing metadata affect image quality?", answer: "No, removing metadata does not affect the visual quality of your image at all. Only the hidden metadata is stripped while the actual image data remains completely unchanged." },
      { question: "Can I remove only GPS data from my photos?", answer: "Yes, MetaClean allows you to selectively remove metadata. You can choose to remove only GPS coordinates while keeping other information like camera settings intact." },
      { question: "Why should I remove metadata before sharing photos?", answer: "Metadata can reveal sensitive information about you including your exact location (GPS), the device you use (camera model), when you took the photo (timestamps), and even your identity (author name). Removing metadata protects your privacy before sharing online." },
      { question: "Does Instagram strip metadata from photos?", answer: "Instagram removes some metadata when you upload photos, but not all of it. Device information and other details may still be preserved. It's best to remove metadata yourself before uploading to any platform." },
      { question: "How does MetaClean protect my privacy?", answer: "MetaClean processes all files entirely in your browser using WebAssembly and modern JavaScript APIs. No data is ever sent to any server. This means your photos and their metadata never leave your device, providing complete privacy protection." },
      { question: "Can I batch process multiple photos?", answer: "Yes, MetaClean offers a Batch Metadata Remover tool that lets you upload and clean multiple files simultaneously. You can download individual cleaned files or get them all as a ZIP archive." },
      { question: "What is the difference between EXIF and metadata?", answer: "EXIF (Exchangeable Image File Format) is a specific type of metadata embedded in images. Metadata is a broader term that includes EXIF data plus other information like IPTC, XMP, and file system metadata. MetaClean removes all types of metadata from your photos." },
      { question: "Do I need to install any software?", answer: "No, MetaClean is a web-based tool that works directly in your browser. There's nothing to download or install. Simply visit the website, upload your photos, and start cleaning metadata instantly." },
      { question: "Can I use MetaClean on my phone?", answer: "Yes, MetaClean is fully responsive and works on all devices including smartphones, tablets, and desktops. The interface adapts to your screen size for the best experience on any device." },
      { question: "How do I know if my photo has metadata?", answer: "Upload your photo to MetaClean's EXIF Viewer tool. It will display all metadata found in your image, organized by category. You can search and filter to find specific fields." },
      { question: "Is MetaClean really free?", answer: "Yes, MetaClean is completely free to use with no hidden fees, subscriptions, or usage limits. We believe privacy tools should be accessible to everyone." },
    ],
    relatedTools: ["remove-gps-from-photo", "exif-viewer", "social-media-cleaner", "batch-metadata-remover"],
  },
  "remove-gps-from-photo": {
    slug: "remove-gps-from-photo",
    title: "Remove GPS from Photo",
    metaTitle: "Remove GPS Coordinates From Photos Free — Location Privacy | MetaClean",
    metaDescription: "Extract and remove GPS coordinates from photos. Protect your location privacy. Free client-side tool that never uploads your files.",
    keywords: [
      "remove GPS from photo",
      "remove GPS coordinates",
      "GPS metadata remover",
      "strip location data from photo",
      "photo location privacy",
      "remove geotag",
      "GPS coordinates extractor",
      "location data remover",
      "remove EXIF GPS",
      "protect photo location",
      "GPS cleaner online",
      "free GPS remover",
    ],
    description: "Extract and display GPS coordinates from your photos. See exactly where a photo was taken and remove location data with one click to protect your privacy.",
    benefits: [
      "See exact GPS coordinates (latitude/longitude) from your photos",
      "View location on Google Maps with one click",
      "Remove GPS data while keeping other EXIF information",
      "Protect your home address and frequent locations",
      "Prevent location tracking through shared photos",
      "100% client-side processing — no server uploads",
    ],
    howItWorks: [
      { step: "01", title: "Upload Photo", description: "Drop your image or click to browse. Supports JPG, PNG, WEBP formats." },
      { step: "02", title: "View GPS Data", description: "See extracted GPS coordinates with latitude, longitude, and altitude if available." },
      { step: "03", title: "Remove GPS", description: "Click 'Remove GPS Only' to strip location data. Download your clean photo." },
    ],
    faqs: [
      { question: "How do I find GPS coordinates in a photo?", answer: "Upload your photo to MetaClean's GPS Remover tool. It will automatically extract and display the GPS coordinates including latitude, longitude, and altitude if available. You can also view the location on Google Maps." },
      { question: "Can GPS data reveal my home address?", answer: "Yes, GPS metadata in photos contains the exact latitude and longitude where the photo was taken. If you take photos at home, this data can be used to determine your home address with high accuracy." },
      { question: "How accurate is GPS data in photos?", answer: "GPS data in photos is typically accurate to within 3-10 meters using smartphone GPS. With WiFi and cell tower triangulation, accuracy can be even better in urban areas. This means someone could determine exactly which building you're in." },
      { question: "Can I remove GPS without affecting other metadata?", answer: "Yes, MetaClean's GPS Remover specifically targets GPS coordinates while leaving all other metadata (camera info, timestamps, settings) intact. This gives you precise control over what information is removed." },
      { question: "Do all photos contain GPS data?", answer: "Not all photos contain GPS data. Photos taken with cameras (not smartphones) typically don't have GPS unless a GPS receiver was attached. However, most modern smartphones record GPS coordinates by default." },
      { question: "How do I disable GPS tagging on my iPhone?", answer: "Go to Settings > Privacy & Services > Location Services. Find your Camera app and set it to 'Never' or 'While Using'. This prevents future photos from recording GPS data, but won't remove GPS from existing photos." },
      { question: "How do I disable GPS tagging on Android?", answer: "Open your Camera app, go to Settings, and disable 'Location tags' or 'Geo-tag'. The exact location varies by manufacturer. You can also disable location services entirely in Settings > Location." },
      { question: "Can someone track me through my photos?", answer: "Yes, if your photos contain GPS metadata, someone can extract the coordinates and determine where you were when the photo was taken. This is why it's important to remove GPS data before sharing photos online." },
      { question: "Does MetaClean show my location on a map?", answer: "Yes, MetaClean's GPS Remover displays your GPS coordinates and provides a direct link to Google Maps showing the exact location where the photo was taken. This helps you understand what location information is exposed." },
      { question: "Is GPS removal different from EXIF removal?", answer: "GPS removal specifically targets only the location coordinates in your photo's metadata. EXIF removal is broader and removes all EXIF data including camera settings, timestamps, and GPS. Choose GPS removal when you want to keep other information." },
      { question: "What happens to my photo quality after GPS removal?", answer: "Nothing — removing GPS coordinates has zero impact on your photo's visual quality. Only the location metadata is stripped while all image data remains perfectly intact." },
      { question: "Can I remove GPS from multiple photos at once?", answer: "Yes, use MetaClean's Batch Metadata Remover to process multiple photos simultaneously. Upload all your photos, and the tool will remove GPS data from each one. Download individually or as a ZIP." },
      { question: "Why do smartphones add GPS data to photos?", answer: "Smartphones add GPS data to enable features like photo organization by location, maps showing where photos were taken, and location-based sharing. While convenient, this creates privacy risks when photos are shared publicly." },
      { question: "Does MetaClean work offline for GPS removal?", answer: "Yes, once the page is loaded, MetaClean can work offline since all GPS extraction and removal happens locally in your browser. You can bookmark the page for offline use." },
      { question: "How do I check if a shared photo has GPS data?", answer: "Download the shared photo and upload it to MetaClean's EXIF Viewer. It will display all metadata including GPS coordinates if present. This helps you understand what information is exposed in photos you receive." },
    ],
    relatedTools: ["remove-photo-metadata", "exif-viewer", "privacy-score-tool", "social-media-cleaner"],
  },
  "exif-viewer": {
    slug: "exif-viewer",
    title: "EXIF Viewer",
    metaTitle: "Free EXIF Viewer Online — Inspect Photo Metadata | MetaClean",
    metaDescription: "View all EXIF metadata in your photos. Inspect camera info, GPS, timestamps, and more. Free client-side EXIF viewer with searchable table.",
    keywords: [
      "EXIF viewer online",
      "view EXIF data",
      "EXIF metadata viewer",
      "photo metadata inspector",
      "check EXIF data",
      "EXIF reader online",
      "camera metadata viewer",
      "EXIF data checker",
      "inspect photo metadata",
      "EXIF info viewer",
      "free EXIF tool",
      "metadata analyzer",
    ],
    description: "Inspect all metadata embedded in your photos. View camera information, GPS coordinates, timestamps, software details, and more in a searchable, organized table.",
    benefits: [
      "View complete EXIF data organized by category",
      "Search and filter metadata fields instantly",
      "See camera make, model, lens, and settings",
      "Check for GPS coordinates and timestamps",
      "Get a privacy score for your photo",
      "100% client-side — your photos never leave your device",
    ],
    howItWorks: [
      { step: "01", title: "Upload Photo", description: "Drag and drop any image or click to browse. Supports JPG, PNG, WEBP." },
      { step: "02", title: "Inspect Metadata", description: "View all EXIF data in a searchable table. Filter by category." },
      { step: "03", title: "Take Action", description: "Use the privacy score to understand risks. Clean metadata if needed." },
    ],
    faqs: [
      { question: "What is EXIF data?", answer: "EXIF (Exchangeable Image File Format) is metadata automatically embedded in photos by cameras and smartphones. It includes technical details like camera settings (aperture, shutter speed, ISO), GPS coordinates, device information, timestamps, and software used for editing." },
      { question: "How do I view EXIF data in a photo?", answer: "Upload your photo to MetaClean's EXIF Viewer. The tool will automatically extract and display all metadata in a searchable, categorized table. You can filter by category (camera, GPS, date, software) or search for specific fields." },
      { question: "Can I view EXIF data on my phone?", answer: "Yes, MetaClean's EXIF Viewer is fully responsive and works on mobile devices. Simply visit the website in your mobile browser and upload your photo to view all metadata." },
      { question: "What information can EXIF data reveal?", answer: "EXIF data can reveal your GPS location, the camera or phone model you used, the date and time the photo was taken, camera settings (which can identify your skill level), software used for editing, and sometimes the author's name." },
      { question: "How do I search for specific metadata fields?", answer: "Use the search bar at the top of the EXIF Viewer to filter metadata fields. You can also click on category tags (Camera, GPS, Date, Software, Author) to quickly filter by type." },
      { question: "What is a privacy score?", answer: "The privacy score is a 0-100 rating that indicates how much sensitive metadata your photo contains. A score of 100 means no metadata was found. GPS data (-40 points) and device info (-20 points) significantly lower the score." },
      { question: "Does every photo have EXIF data?", answer: "Most photos from smartphones and digital cameras contain EXIF data. However, photos that have been edited, screenshot, or processed by social media platforms may have had some or all EXIF data removed." },
      { question: "Can I copy EXIF data from a photo?", answer: "MetaClean's EXIF Viewer displays all metadata in a readable format. You can reference the displayed information, though the tool doesn't currently support copying individual fields. You can take a screenshot of the results." },
      { question: "How is EXIF data different from metadata?", answer: "EXIF is a specific type of metadata used in images. Metadata is a broader term that includes EXIF (image settings, GPS, camera info), IPTC (captions, keywords, copyright), and XMP (extended metadata). MetaClean's EXIF Viewer shows all types of image metadata." },
      { question: "Why do I need to check EXIF data?", answer: "Checking EXIF data helps you understand what information is exposed in your photos before sharing them. You might discover GPS coordinates that reveal your location, device information that identifies you, or timestamps that expose your schedule." },
      { question: "Does MetaClean support RAW photo formats?", answer: "MetaClean currently supports JPG, JPEG, PNG, and WEBP formats. RAW formats from specific camera manufacturers (CR2, NEF, ARW, etc.) are not currently supported, but we're working on adding more formats." },
      { question: "How do I remove metadata after viewing it?", answer: "After inspecting your photo in the EXIF Viewer, use MetaClean's Photo Metadata Remover to clean the metadata. You can selectively choose which fields to remove or clean everything at once." },
      { question: "Is the EXIF Viewer accurate?", answer: "Yes, MetaClean uses the exifr library for accurate EXIF parsing. It correctly reads all standard EXIF, IPTC, and XMP metadata fields. The displayed information directly reflects what's embedded in your photo file." },
      { question: "Can I view EXIF data before and after cleaning?", answer: "Yes, upload your photo to the EXIF Viewer to see the before state. After cleaning with the Photo Metadata Remover, upload the cleaned version to the EXIF Viewer to verify the metadata has been removed." },
      { question: "What does the category filter show?", answer: "The category filter groups metadata fields into logical categories: Camera (make, model, settings), GPS (location data), Date (timestamps), Software (editing tools), and Author (creator information). This makes it easy to find specific types of information." },
    ],
    relatedTools: ["remove-photo-metadata", "remove-gps-from-photo", "privacy-score-tool", "social-media-cleaner"],
  },
  "social-media-cleaner": {
    slug: "social-media-cleaner",
    title: "Social Media Cleaner",
    metaTitle: "Social Media Photo Cleaner — Remove Metadata Before Posting | MetaClean",
    metaDescription: "Clean photos before posting on social media. Detect device info, GPS, and date exposure. Free client-side tool for Instagram, Facebook, TikTok.",
    keywords: [
      "social media photo cleaner",
      "clean photos before posting",
      "Instagram photo privacy",
      "Facebook metadata remover",
      "remove metadata before sharing",
      "social media privacy tool",
      "TikTok photo cleaner",
      "photo privacy for social media",
      "clean EXIF for Instagram",
      "remove GPS before posting",
      "social media safety tool",
      "private photo sharing",
    ],
    description: "Analyze your photos for privacy risks before posting on social media. Detect device information, GPS coordinates, and creation dates. One-click clean for safe sharing on Instagram, Facebook, TikTok, and more.",
    benefits: [
      "Detect device model that can identify you",
      "Find GPS coordinates that reveal your location",
      "Identify timestamps that expose when photos were taken",
      "One-click clean for all social media platforms",
      "Privacy risk analysis before you post",
      "100% client-side — photos never leave your device",
    ],
    howItWorks: [
      { step: "01", title: "Upload Photo", description: "Drop your image or click to browse. Analyze before posting." },
      { step: "02", title: "Review Risks", description: "See privacy warnings for device info, GPS, dates, and author data." },
      { step: "03", title: "Clean & Share", description: "Click 'Clean for Social Media' and download your safe photo." },
    ],
    faqs: [
      { question: "Why should I clean photos before social media?", answer: "Social media platforms may not fully strip all metadata from your photos. Device information, GPS coordinates, and timestamps can still be exposed, revealing your identity, location, and schedule. Cleaning photos before posting protects your privacy." },
      { question: "Does Instagram remove metadata from photos?", answer: "Instagram strips some metadata when you upload photos, but not all of it. Device information and some other details may still be preserved. It's safer to remove metadata yourself before uploading to ensure complete privacy." },
      { question: "Does Facebook remove EXIF data?", answer: "Facebook removes most EXIF data when you upload photos, but the process isn't always complete. Some metadata may survive the upload process. For maximum privacy, clean your photos before sharing on Facebook." },
      { question: "What privacy risks exist on social media?", answer: "Shared photos can expose your device model (identifying your phone), GPS coordinates (revealing your location), creation timestamps (exposing your schedule), and author information (linking to your identity). These details can be used for tracking, stalking, or social engineering." },
      { question: "How does the Social Media Cleaner work?", answer: "Upload your photo and MetaClean analyzes it for privacy risks. It detects device information, GPS coordinates, timestamps, and author data. Each risk is flagged with a severity level. Click 'Clean for Social Media' to remove all sensitive metadata." },
      { question: "What does 'Clean for Social Media' remove?", answer: "The Social Media Cleaner removes GPS coordinates, device model information, timestamps, and author data while preserving the photo's visual quality. Software tags are kept since they're less privacy-sensitive." },
      { question: "Can someone find me through social media photos?", answer: "Yes, if photos contain GPS metadata, someone can extract coordinates and determine your location. Device information can help identify you across platforms. Timestamps reveal when you're active and your daily patterns." },
      { question: "Is this tool safe for private photos?", answer: "Yes, MetaClean processes all photos entirely in your browser. No data is ever sent to any server. Your private photos remain completely private — even MetaClean can't see them." },
      { question: "What social media platforms should I clean photos for?", answer: "Clean photos before posting on any platform: Instagram, Facebook, TikTok, Twitter/X, LinkedIn, Snapchat, Pinterest, YouTube, and dating apps like Tinder and Bumble. Each platform handles metadata differently." },
      { question: "Does TikTok remove metadata from videos?", answer: "TikTok processes videos and may remove some metadata, but the handling varies. For photos posted alongside videos, metadata may not be fully stripped. Always clean photos before uploading to any platform." },
      { question: "How do I check if a shared photo is safe?", answer: "Download the photo and upload it to MetaClean's EXIF Viewer or Social Media Cleaner. The tool will analyze it for privacy risks and show you exactly what metadata is present." },
      { question: "Should I clean photos for LinkedIn?", answer: "Yes, even professional photos on LinkedIn can contain metadata. Device information, GPS from office locations, and timestamps can reveal information about you. Clean photos before uploading to LinkedIn for maximum privacy." },
      { question: "Can metadata be used for stalking?", answer: "Yes, metadata — especially GPS coordinates — can be used by stalkers to track your movements and determine your locations. Timestamps reveal your schedule, and device info helps identify you across platforms." },
      { question: "What is the privacy score for social media?", answer: "The privacy score indicates how safe your photo is for sharing. A high score (90+) means few privacy risks. Lower scores indicate sensitive metadata like GPS (-40 points) or device info (-20 points) that should be removed before posting." },
      { question: "Do I need to clean every photo I post?", answer: "It's good practice to clean photos that contain sensitive metadata. Use MetaClean's EXIF Viewer to quickly check if a photo has risky metadata, then clean it with the Social Media Cleaner before posting." },
    ],
    relatedTools: ["remove-photo-metadata", "remove-gps-from-photo", "exif-viewer", "privacy-score-tool"],
  },
  "batch-metadata-remover": {
    slug: "batch-metadata-remover",
    title: "Batch Metadata Remover",
    metaTitle: "Batch Metadata Remover — Clean Multiple Files at Once | MetaClean",
    metaDescription: "Remove metadata from multiple files simultaneously. Batch process photos and PDFs. Download as ZIP. Free client-side tool.",
    keywords: [
      "batch metadata remover",
      "remove metadata from multiple files",
      "bulk EXIF removal",
      "batch photo cleaner",
      "mass metadata removal",
      "batch process photos",
      "bulk file cleaner",
      "ZIP download metadata remover",
      "multiple file metadata remover",
      "batch PDF cleaner",
      "enterprise metadata removal",
      "bulk privacy tool",
    ],
    description: "Upload and clean metadata from multiple files at once. Supports photos and PDFs. Track progress for each file and download all cleaned files as a ZIP archive.",
    benefits: [
      "Process multiple files in one session",
      "Support for both photos and PDFs",
      "Real-time progress tracking",
      "Individual file status monitoring",
      "Download all cleaned files as ZIP",
      "100% client-side processing",
    ],
    howItWorks: [
      { step: "01", title: "Upload Files", description: "Drag and drop multiple files or click to browse. Supports JPG, PNG, WEBP, PDF." },
      { step: "02", title: "Clean All", description: "Click 'Clean All Files' to process the entire batch with progress tracking." },
      { step: "03", title: "Download ZIP", description: "Download all cleaned files as a single ZIP archive or individually." },
    ],
    faqs: [
      { question: "How many files can I process at once?", answer: "MetaClean can handle dozens of files in a single batch. The exact number depends on your device's processing power and memory. Each file is processed sequentially with real-time progress tracking." },
      { question: "What file formats are supported for batch processing?", answer: "MetaClean supports JPG, JPEG, PNG, WEBP image files and PDF documents for batch processing. The tool automatically detects the file type and applies the appropriate cleaning method." },
      { question: "How do I download all cleaned files?", answer: "After processing is complete, click the 'Download ZIP' button to download all cleaned files as a single ZIP archive. You can also download files individually by clicking the download button next to each completed file." },
      { question: "Does batch processing affect quality?", answer: "No, batch processing has the same effect as processing files individually. Each file is cleaned independently with no quality loss. The batch mode simply automates the process for efficiency." },
      { question: "Can I mix photos and PDFs in one batch?", answer: "Yes, MetaClean supports mixed batches of photos (JPG, PNG, WEBP) and PDF documents. The tool automatically detects each file type and applies the appropriate metadata removal method." },
      { question: "What if one file fails to process?", answer: "If a file fails to process, it's marked with an error status while other files continue processing. You can see which files succeeded and which failed, then retry the failed ones individually." },
      { question: "Is batch processing slower than individual?", answer: "Batch processing processes files sequentially, so total time depends on the number and size of files. However, it's more convenient than processing files one at a time, and the progress bar shows you exactly where you are." },
      { question: "Can I remove specific metadata in batch mode?", answer: "Currently, batch mode applies a comprehensive clean that removes GPS, camera info, device data, software tags, and timestamps from images, and all metadata from PDFs. For selective cleaning, use the individual tool pages." },
      { question: "How does the ZIP download work?", answer: "After processing, click 'Download ZIP' and MetaClean creates a ZIP archive containing all cleaned files using JavaScript. The ZIP is generated entirely in your browser — no server involved." },
      { question: "Can I track which files have been processed?", answer: "Yes, each file shows its current status: Pending, Processing (with spinner), Completed (green check), or Error (red badge). The overall progress bar shows the percentage complete." },
      { question: "Does batch processing work offline?", answer: "Yes, once the page is loaded, batch processing works entirely offline. All processing happens in your browser using client-side JavaScript. No internet connection is required after the initial page load." },
      { question: "Can I remove files from the batch before processing?", answer: "Yes, each file has a remove button (X) that lets you remove it from the batch before processing starts. You can also clear all files and start over." },
      { question: "What metadata is removed in batch mode?", answer: "For images: GPS coordinates, camera make/model, device serial numbers, software tags, and timestamps. For PDFs: author, title, subject, creator, producer, and keywords." },
      { question: "Is there a file size limit for batch processing?", answer: "There's no strict file size limit, but very large files (hundreds of MB) may take longer to process and require more browser memory. For best results, keep individual files under 50MB." },
      { question: "Can I use batch processing on mobile?", answer: "Yes, the Batch Metadata Remover is fully responsive and works on mobile devices. The drag-and-drop zone works with touch, and you can select multiple files from your mobile file browser." },
    ],
    relatedTools: ["remove-photo-metadata", "remove-pdf-metadata", "remove-text-metadata", "exif-viewer"],
  },
  "privacy-score-tool": {
    slug: "privacy-score",
    title: "Privacy Score Calculator",
    metaTitle: "Privacy Score Calculator — Rate Photo Privacy Risk | MetaClean",
    metaDescription: "Calculate privacy score for your photos from 0-100. See detailed risk breakdown. Detect GPS, device info, timestamps. Free client-side tool.",
    keywords: [
      "privacy score calculator",
      "photo privacy score",
      "privacy risk assessment",
      "EXIF privacy score",
      "metadata risk calculator",
      "photo privacy rating",
      "privacy score checker",
      "image privacy analyzer",
      "metadata privacy score",
      "GPS privacy risk",
      "device info privacy risk",
      "free privacy tool",
    ],
    description: "Calculate a privacy score from 0-100 for your photos. Get a detailed breakdown of privacy risks including GPS exposure, device identification, timestamp leaks, and more.",
    benefits: [
      "Instant privacy score from 0-100",
      "Detailed risk breakdown by category",
      "Visual score circle with grade",
      "Risk level classification (Safe to Critical)",
      "Specific penalty points for each issue",
      "100% client-side analysis",
    ],
    howItWorks: [
      { step: "01", title: "Upload Photo", description: "Drop your image or click to browse. Any format supported." },
      { step: "02", title: "Get Score", description: "See your privacy score, grade, and risk level instantly." },
      { step: "03", title: "Review & Act", description: "Review detailed breakdown. Use recommended tools to fix issues." },
    ],
    faqs: [
      { question: "How is the privacy score calculated?", answer: "The privacy score starts at 100 and deducts points for each type of sensitive metadata found: GPS (-40), Device Info (-20), Timestamps (-10), Author (-10), Software (-10). A score of 100 means no metadata was found. The lowest possible score is 0." },
      { question: "What does a score of 100 mean?", answer: "A privacy score of 100 means no sensitive metadata was detected in your photo. This is the best possible score and indicates the photo is safe to share without any privacy concerns related to metadata." },
      { question: "What does a low privacy score mean?", answer: "A low privacy score (below 50) indicates significant privacy risks. Your photo likely contains GPS coordinates that reveal your location, device information that identifies you, and other sensitive metadata that should be removed before sharing." },
      { question: "How accurate is the privacy score?", answer: "The privacy score is based on industry-standard privacy risk categories. GPS exposure is weighted highest (-40 points) because it directly reveals your location. Device info (-20) can identify you. Timestamps, author, and software (-10 each) are less critical but still relevant." },
      { question: "What is the risk level?", answer: "Risk levels classify your score: Safe (90-100), Low Risk (70-89), Medium Risk (50-69), High Risk (30-49), Critical (0-29). Each level has specific recommendations for what metadata to remove." },
      { question: "Should I always aim for a score of 100?", answer: "A score of 100 is ideal for maximum privacy, but not always necessary. For example, if you're sharing photos with family, keeping timestamps might be fine. For public sharing on social media, aim for 90+ by removing GPS and device info." },
      { question: "How do I improve my privacy score?", answer: "Use MetaClean's tools to remove the detected metadata. Remove GPS coordinates (-40 points recovered), device info (-20), timestamps (-10), and author data (-10). The Photo Metadata Remover can clean all these at once." },
      { question: "Can I check multiple photos?", answer: "Yes, you can upload different photos one at a time to check their privacy scores. Use this to compare photos before deciding which ones are safe to share." },
      { question: "What metadata categories affect the score?", answer: "Five categories affect the score: GPS Location (critical, -40 pts), Device Information (high, -20 pts), Timestamps (medium, -10 pts), Author Information (medium, -10 pts), and Software Tags (low, -10 pts)." },
      { question: "Is the score different for different file types?", answer: "The scoring system is designed for image files (JPG, PNG, WEBP). PDF files have different metadata fields, but the same general categories apply. The score provides a useful privacy indicator for any supported file type." },
      { question: "What does 'Critical' risk level mean?", answer: "A Critical risk level (score below 30) means your photo contains highly sensitive metadata, most likely GPS coordinates that reveal your exact location. This is the highest privacy risk and should be addressed before sharing." },
      { question: "Can I share the privacy score with others?", answer: "You can take a screenshot of the privacy score results to share with others. This is useful for showing colleagues or family members the privacy risks in their photos." },
      { question: "Does the tool store my privacy scores?", answer: "No, all score calculations happen in your browser. No data is stored or transmitted. Each time you upload a photo, the score is calculated fresh from the metadata in that specific file." },
      { question: "What's the difference between score and risk level?", answer: "The score is a numerical value (0-100) showing exact privacy status. The risk level is a category (Safe, Low, Medium, High, Critical) that provides a quick interpretation of the score. Both are displayed together for clarity." },
      { question: "How do I use the scoring breakdown?", answer: "The scoring breakdown shows each metadata category, whether it was detected, and the penalty applied. Green checkmarks indicate clean categories. Red warnings show detected issues with their point penalties. Use this to understand exactly what needs fixing." },
    ],
    relatedTools: ["exif-viewer", "remove-photo-metadata", "remove-gps-from-photo", "social-media-cleaner"],
  },
  "remove-pdf-metadata": {
    slug: "remove-pdf-metadata",
    title: "Remove PDF Metadata",
    metaTitle: "Remove PDF Metadata Online Free — Author, Title, Keywords | MetaClean",
    metaDescription: "Remove author, title, creator, producer, subject, and keywords from PDF files. Free client-side tool. Content preserved, metadata cleaned.",
    keywords: [
      "remove PDF metadata",
      "PDF metadata remover",
      "strip PDF properties",
      "remove author from PDF",
      "PDF privacy tool",
      "clean PDF metadata",
      "remove PDF properties",
      "PDF document cleaner",
      "free PDF metadata remover",
      "client-side PDF tool",
      "remove PDF creator",
      "PDF author remover",
    ],
    description: "Remove author, title, subject, creator, producer, and keywords from PDF documents. Your content is preserved while metadata is completely cleaned.",
    benefits: [
      "Remove author name and identity information",
      "Strip document title and subject",
      "Remove creator and producer software info",
      "Delete keywords and search terms",
      "Preserve all document content and formatting",
      "100% client-side processing",
    ],
    howItWorks: [
      { step: "01", title: "Upload PDF", description: "Drag and drop your PDF or click to browse." },
      { step: "02", title: "Review Metadata", description: "See all detected metadata including author, title, creator, and more." },
      { step: "03", title: "Clean & Download", description: "Select fields to remove and click Clean. Download your clean PDF." },
    ],
    faqs: [
      { question: "What metadata do PDF files contain?", answer: "PDF files can contain: Author name, Document title, Subject, Keywords, Creator software (e.g., 'Microsoft Word'), Producer (e.g., 'Adobe PDF Library'), Creation date, and Modification date. This information can identify the document's creator." },
      { question: "How do I remove metadata from a PDF?", answer: "Upload your PDF to MetaClean's PDF Metadata Remover. The tool will display all detected metadata. Select which fields to remove (author, title, creator, etc.) and click Clean. Download the cleaned PDF with all selected metadata removed." },
      { question: "Does removing metadata affect PDF content?", answer: "No, removing metadata does not affect the content, formatting, images, or layout of your PDF. Only the document properties (author, title, keywords, etc.) are removed while the actual document remains unchanged." },
      { question: "Can I remove all metadata at once?", answer: "Yes, by default all metadata fields are selected for removal. You can also selectively choose which fields to remove if you want to keep some information while removing others." },
      { question: "Why should I remove PDF metadata?", answer: "PDF metadata can reveal the author's name, the software used to create the document, creation dates, and other identifying information. This is important for privacy when sharing documents publicly or with unknown recipients." },
      { question: "Is MetaClean safe for confidential PDFs?", answer: "Yes, MetaClean processes PDFs entirely in your browser. No file is ever sent to any server. Your confidential documents remain completely private — even MetaClean can't access them." },
      { question: "What PDF fields can be removed?", answer: "MetaClean can remove: Author, Title, Subject, Creator, Producer, Keywords, Creation Date, and Modification Date. These are the standard metadata fields defined in the PDF specification." },
      { question: "Can I remove metadata from password-protected PDFs?", answer: "MetaClean can process PDFs that don't require a password to open. If your PDF requires a password to view, you'll need to enter the password before MetaClean can process it." },
      { question: "Does this work on scanned PDFs?", answer: "Yes, MetaClean works on any PDF file including scanned documents. Scanned PDFs often contain metadata about the scanning software and settings, which MetaClean can remove." },
      { question: "How do I verify metadata was removed?", answer: "After cleaning, upload the cleaned PDF to MetaClean's EXIF Viewer or use Adobe Acrobat's Properties dialog to verify that the metadata fields have been cleared." },
      { question: "Can I batch clean multiple PDFs?", answer: "Yes, use MetaClean's Batch Metadata Remover to process multiple PDFs simultaneously. Upload all your PDFs, clean them in one go, and download as a ZIP archive." },
      { question: "What's the difference between Author and Creator?", answer: "Author is the person who wrote or created the content. Creator is the software application used to create the PDF (e.g., 'Microsoft Word', 'LaTeX'). Both can reveal identifying information about you." },
      { question: "Do PDFs from scanners have metadata?", answer: "Yes, scanned PDFs often contain metadata including the scanning software name, scanner model, and creation date. Some scanning applications also add author information." },
      { question: "Can I remove metadata from PDF forms?", answer: "Yes, MetaClean can remove metadata from PDF forms. However, form data (filled-in fields) is separate from metadata and won't be affected by the cleaning process." },
      { question: "Is this tool compliant with privacy regulations?", answer: "MetaClean helps you comply with privacy regulations like GDPR by providing a tool to remove identifying information from documents before sharing. All processing is client-side for maximum data protection." },
    ],
    relatedTools: ["remove-photo-metadata", "remove-text-metadata", "batch-metadata-remover", "privacy-score-tool"],
  },
  "remove-text-metadata": {
    slug: "remove-text-metadata",
    title: "Clean Text Files",
    metaTitle: "Clean Text Files Online — Remove BOM, Unicode, Hidden Characters | MetaClean",
    metaDescription: "Remove hidden Unicode characters, BOM markers, and invisible tracking data from TXT, CSV, JSON, XML files. Free client-side tool.",
    keywords: [
      "clean text files",
      "remove BOM from file",
      "remove hidden Unicode",
      "text file cleaner",
      "CSV cleaner online",
      "JSON file cleaner",
      "XML metadata remover",
      "remove invisible characters",
      "text file privacy",
      "BOM remover online",
      "normalize line endings",
      "remove tracking characters",
    ],
    description: "Remove hidden Unicode characters, BOM markers, control characters, and invisible tracking data from text files. Supports TXT, CSV, JSON, and XML formats.",
    benefits: [
      "Remove BOM (Byte Order Mark) characters",
      "Strip invisible Unicode characters",
      "Remove non-printable control characters",
      "Normalize inconsistent line endings",
      "Detect and display hidden characters",
      "100% client-side processing",
    ],
    howItWorks: [
      { step: "01", title: "Upload File", description: "Drop your TXT, CSV, JSON, or XML file or click to browse." },
      { step: "02", title: "Scan Results", description: "See detected issues: BOM, invisible chars, control chars, line endings." },
      { step: "03", title: "Clean & Download", description: "Select cleaning options and download your clean file." },
    ],
    faqs: [
      { question: "What are hidden characters in text files?", answer: "Hidden characters include BOM (Byte Order Mark), zero-width spaces, invisible Unicode formatting characters, non-printable control characters, and inconsistent line endings. These are invisible to humans but can be read by software." },
      { question: "What is a BOM (Byte Order Mark)?", answer: "A BOM is a special Unicode character (U+FEFF) placed at the beginning of a text file to indicate its encoding. While sometimes useful, BOMs can cause issues with certain software and should be removed for compatibility." },
      { question: "Why should I remove hidden characters?", answer: "Hidden characters can cause software compatibility issues, reveal information about the file's origin, introduce subtle bugs in code, and potentially be used for tracking. Removing them ensures clean, compatible text files." },
      { question: "What text formats are supported?", answer: "MetaClean supports TXT (plain text), CSV (comma-separated values), JSON (JavaScript Object Notation), and XML (eXtensible Markup Language) files." },
      { question: "How do I detect hidden characters?", answer: "Upload your file to MetaClean's Text File Cleaner. It automatically scans for BOM characters, invisible Unicode, control characters, and inconsistent line endings, showing you exactly what was found." },
      { question: "Does cleaning affect my data?", answer: "No, cleaning only removes invisible characters that don't affect the readable content of your file. Your actual text, numbers, and data remain completely unchanged." },
      { question: "What are line endings and why normalize them?", answer: "Different operating systems use different characters for line breaks: Windows uses CRLF, Unix uses LF, old Macs used CR. Inconsistent line endings can cause display and processing issues. Normalizing ensures consistent formatting." },
      { question: "Can I clean CSV files without affecting data?", answer: "Yes, MetaClean's text cleaning only targets invisible characters. Your CSV data, column headers, and formatting remain completely intact. Only hidden Unicode and control characters are removed." },
      { question: "How do invisible characters get in my files?", answer: "Hidden characters can come from text editors, copy-pasting from web pages, email clients, word processors, or data exports from various systems. Some applications automatically add BOM or special formatting characters." },
      { question: "Can I clean JSON files for API use?", answer: "Yes, cleaning JSON files removes hidden characters that might cause parsing errors in APIs. This is especially useful when combining data from multiple sources that may use different encodings." },
      { question: "What are control characters?", answer: "Control characters are non-printable characters in the ASCII range (0-31 and 127) that were originally designed for device control. They're invisible in normal text but can cause issues in modern software." },
      { question: "Can I batch clean multiple text files?", answer: "Yes, use MetaClean's Batch Metadata Remover to process multiple text files at once. Upload all your files and clean them in a single session." },
      { question: "Does cleaning change file encoding?", answer: "No, MetaClean preserves the original file encoding. It only removes specific invisible characters while maintaining UTF-8 or whatever encoding your file uses." },
      { question: "How do I know if my file has hidden characters?", answer: "Upload your file to MetaClean's Text Cleaner. The scan results will clearly show which types of hidden characters were found: BOM, Invisible Unicode, Control Characters, or Inconsistent Line Endings." },
      { question: "Is this useful for code files?", answer: "Yes, hidden characters in code files can cause subtle bugs that are hard to diagnose. Cleaning ensures your code is free of invisible characters that might cause unexpected behavior." },
    ],
    relatedTools: ["remove-photo-metadata", "remove-pdf-metadata", "batch-metadata-remover", "exif-viewer"],
  },
};

export const toolOrder = [
  "remove-photo-metadata",
  "remove-gps-from-photo",
  "exif-viewer",
  "social-media-cleaner",
  "batch-metadata-remover",
  "privacy-score",
  "remove-pdf-metadata",
  "remove-text-metadata",
];
